### ISSUE TITLE
Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by alkshendra-SEQ** [Finch-API/react-finch-connect#12]
Getting this while integrating any of the callbacks (onSuccess, onClose)

It seems like the Finch iframe is not able to access the `window.parent`, probably because of the headers. Can someone mention the relevant config to resolve this?

<img width="414" alt="Screenshot 2022-01-04 at 11 39 46 AM" src="https://user-images.githubusercontent.com/54621153/148016847-f76a8311-776c-4b36-b560-fa4cb9305832.png">

**Comment by alkshendra-SEQ** [comment]
I checked the source and realized this is because you are using `document.referrer`

<img width="699" alt="Screenshot 2022-01-09 at 8 09 50 PM" src="https://user-images.githubusercontent.com/54621153/148687238-7fde8313-a174-4814-97bf-12781b746123.png">

We had set the `Referrer-Policy: no-referrer` header which caused the issue.
I recommend you add a section on recommended headers in the docs.
@aren55555 @jerzzhang @KarthikBhaskara

**Comment by jamesicon** [comment]
@aren55555 It would be great if this was solved within the lib, we also had to loosen our referrer policy to make this work and would like to not have to do that.
