### ISSUE TITLE
Allow React 17 as a peer dependency

### ISSUE THREAD

**Issue by relsunkaev** [Finch-API/react-finch-connect#17]
We use React 17 and cannot generate a lock file without `--force`. So far, we've had no issues with this package using React 17 so it would be great if that dependency could be unpinned.

**Comment by yuyokk** [comment]
same here :(

**Comment by rluncasu** [comment]
another one encountering the same issue

**Comment by relsunkaev** [comment]
Filed a [Jira Service Desk](https://tryfinch.atlassian.net/servicedesk/customer/portal/1/SUPPORT-185) issue. Hopefully that helps with visibility for them.
