### ISSUE TITLE
BASE_FINCH_CONNECT_URI set to localhost

### ISSUE THREAD

**Issue by jamesicon** [Finch-API/react-finch-connect#35]
Am attempting to set this up and noticed that in the github files the connect uri is
`const BASE_FINCH_CONNECT_URI = 'https://connect.tryfinch.com/';`

but then when I load the package and component into my app, the dist for the index.js file shows this
`const BASE_FINCH_CONNECT_URI = 'http://localhost:3000/';`

which breaks the connect from opening in an iframe since the URI isn't right.

**Comment by aneeshvaidya** [comment]
Thanks for filing this issue! We've released 2.6.2 to npm that has resolved this bug!
