### ISSUE TITLE
Typescript types?

### ISSUE THREAD

**Issue by owen-c** [Finch-API/react-finch-connect#4]
Can you add Typescript types to the project? Makes it annoying to integrate in a Typescript project without them. See below for some types I threw together that you can use as a starting point

```
declare module 'react-finch-connect' {
  export function useFinchConnect(options: Options): { open: () => void };

  export interface Options {
    clientId: string;
    products?: string[];
    mode?: string;
    manual?: boolean;
    payrollProvider?: string;
    sandbox?: boolean;
    onSuccess?: (obj: { code: string }) => void;
    onError?: (obj: { errorMessage: string }) => void;
    onClose?: () => void;
  }
}
```

**Comment by aren55555** [comment]
Closing - version 2.5.0 of the library was pushed to [NPM](https://www.npmjs.com/package/react-finch-connect) tonight and includes this feature.
